/**
 * @Class BAArrayUtil.ets
 * @Author boai
 * @DateTime 2024/7/4 09:37:54
 */

export class BACommonConstants {

  //布局
  static readonly PERCENT_FULL = '100%'
  static readonly PERCENT_EXCEPT_NAVI = '96%'
  static readonly PERCENT_EXCEPT_TABBAR = '96%'
  static readonly PERCENT_EXCEPT_TABBARANDNAVI = '91%'
  static readonly NAVIGATIONBAR_HEIGHT = 64

  static readonly IMAGE_WIDTH_RIGHTARROW = 20

  //字体
  static readonly FONT_SIZE_NAVI_TITLE = 20

  //提示语
  static readonly TIP_FUNCTIONNOTDEVELOP = '此功能正在努力开发中...'



}

